// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPehMA6Fnl4SldBGosSVtYSZG6Rerjh4Y',
    appId: '1:586612811469:web:557d0109ea8b0848062b84',
    messagingSenderId: '586612811469',
    projectId: 'tak-256',
    authDomain: 'tak-256.firebaseapp.com',
    storageBucket: 'tak-256.appspot.com',
    measurementId: 'G-GFGX971HEM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsXDku84oyhBq5TnO-zRs7zMAhK_PzYVY',
    appId: '1:586612811469:android:932b0b5cadb6d12d062b84',
    messagingSenderId: '586612811469',
    projectId: 'tak-256',
    storageBucket: 'tak-256.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtkSihzTBGJ3Jp9Ck7hY3crNt0E42E_kM',
    appId: '1:586612811469:ios:f280e0fded0d2d63062b84',
    messagingSenderId: '586612811469',
    projectId: 'tak-256',
    storageBucket: 'tak-256.appspot.com',
    iosClientId: '586612811469-je8o00rmrofcp53bn4j5gibbc3lhtlmh.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiktok',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtkSihzTBGJ3Jp9Ck7hY3crNt0E42E_kM',
    appId: '1:586612811469:ios:bbf7a3954c3152bb062b84',
    messagingSenderId: '586612811469',
    projectId: 'tak-256',
    storageBucket: 'tak-256.appspot.com',
    iosClientId: '586612811469-9tibf5ud2kuo6v5j0v767iiqssu4rq17.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiktok.RunnerTests',
  );
}
